import { createRequire } from 'module'
const require = createRequire(import.meta.url)
const version = require("baileys/package.json").version 
global.require = require
global.language = "id"
global.nomerOwner ="6285254337661"
global.nomerOwner2 =""
global.runWith = "Replit"
global.ownerName = "RhmttCore"
global.botName = "Ciyo"
global.sessionName ="session"
global.docType = "docx"
global.Qoted = "ftoko"
global.autoBio = true
global.baileysMd = true
global.antiSpam = true
//global.multi = true
//global.prefa = "!"
global.fake = botName
global.Console = false
global.copyright = `RhmttCore`
global.baileysVersion = `baileys ${version}`
global.fake1 ="Ciyo"
global.packName = "Ciyo"
global.authorName = "RhmttCore"
global.replyType = "web"
global.setwelcome = "type2"
global.autoblockcmd = false
global.autoReport = true
global.autoLevel = true
global.autoSticker = false
global.gamewaktu = 60
global.limitCount = 30 // limit
global.Intervalmsg = 1000 //second
global.apikey = " " //lolhuman